version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    env_file:
      - ./keycloak.env
    ports:
      - "8080:8080"
    command: ["start-dev"]
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

  mariadb:
    image: mariadb:11.3.2
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  schedule-ease-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - mariadb
      - keycloak
#    volumes:
#      - type: bind
#        source: .
#        target: /app #reflect changes for dev purpose
#        consistency: cached

volumes:
  keycloak_data:
  mariadb-data:
    driver: local
